frontend:
    resource: '@FrontendBundle/Controller/'
    type: annotation


#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security_check:
    path:     /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

