# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
  jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
  array_serialization_visitor:
    class: AppBundle\Helper\ArraySerializationVisitor
    public: true
    calls:
      - method: setOptions
        arguments:
          - '%jms_serializer.json_serialization_visitor.options%'
    arguments:
      - '@jms_serializer.naming_strategy'
      - '@jms_serializer.accessor_strategy'
    tags:
      - { name: 'jms_serializer.serialization_visitor', format: 'array' }
